=== gitpan/ASNMTAP/plugins/templates/dtd/email-upgrade-1.0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY AUTHOR "Alex Peeters">
<!ENTITY EMAIL "Alex.Peeters@citap.com">
<!ENTITY PURPOSE "2005/11/15, dtd schema v1.0 for Check Upgrade Email by XML">

<!ELEMENT BaseServiceReport (Ressource)>
<!ELEMENT Ressource (Server, Name, Date, Time, Environment, ErrorStack, ErrorDetail)>
<!ELEMENT Server (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Time (#PCDATA)>
<!ELEMENT Environment (#PCDATA)>
<!ELEMENT ErrorStack (#PCDATA)>
<!ELEMENT ErrorDetail (#PCDATA)>

=== gitpan/ASNMTAP/plugins/templates/xml/email-upgrade-1.0.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE BaseServiceReport SYSTEM "dtd/email-upgrade-1.0.dtd">

<BaseServiceReport>
  <Ressource>
    <Server>Server ...</Server>
    <Name>Name Service to Report</Name>
    <Date>yyyy/mm/dd</Date>
    <Time>hh:mm:ss</Time>
    <Environment>PROD</Environment>
	<ErrorStack><![CDATA[ErrorStack .1.]]></ErrorStack>
    <ErrorDetail><![CDATA[ErrorDetail .1.]]></ErrorDetail>
  </Ressource>
</BaseServiceReport>
